name: Android Build with Termux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Verify Nix Installation
        run: nix --version

      - name: Install Cachix
        run: nix-env -iA cachix -f https://cachix.org/api/v1/install

      - name: Configure Nix for Trusted Users
        run: |
          echo "trusted-users = root ${USER}" | sudo tee -a /etc/nix/nix.conf
          sudo pkill nix-daemon

      - name: Use Devenv Cache from Cachix
        run: cachix use devenv

      - name: Install Devenv
        run: nix-env -iA devenv -f https://github.com/NixOS/nixpkgs/tarball/nixpkgs-unstable

      - name: Initialize Devenv Environment
        run: devenv init
        
