name: Setup Repo and Push Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to work with
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Git (in case it's not already configured)
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Create a file or modify something to commit
      - name: Modify repository files
        run: |
          echo "This is a change from GitHub Actions" >> newfile.txt
          cat newfile.txt

      # Add, commit, and push the changes
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Automated changes from GitHub Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token allows GitHub Actions to push changes
