name: Android Build with Termux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Verify Nix Installation
        run: nix --version

      - name: Download and Install Devenv
        run: |
          nix-env -iA nixpkgs.devenv
          echo "Devenv installed successfully"

      - name: Verify Devenv Installation
        run: devenv --version

      - name: Initialize Devenv Environment
        run: devenv init

      - name: Build the Devenv Shell
        run: devenv shell

      - name: Run Devenv Tests
        run: devenv test
