name: Android Build with Termux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: ["armeabi-v7a", "arm64-v8a"]
        api-level: [24, 28]  # API 24 for ARMv7, API 28 for ARM64

    steps:
      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Verify Nix Installation
        run: nix --version

      - name: Install Cachix
        run: nix-env -iA cachix -f https://cachix.org/api/v1/install

      - name: Configure Nix for Trusted Users
        run: |
          echo "trusted-users = root ${USER}" | sudo tee -a /etc/nix/nix.conf
          sudo pkill nix-daemon

      - name: Use Devenv Cache from Cachix
        run: cachix use devenv

      - name: Install Devenv
        run: nix-env -iA devenv -f https://github.com/NixOS/nixpkgs/tarball/nixpkgs-unstable

      - name: Set Up Android Emulator with Termux
        run: |
          echo 'with import <nixpkgs> {};
          
          androidenv.emulateApp {
            name = "emulate-Termux";
            platformVersion = "${{ matrix.api-level }}";
            abiVersion = "${{ matrix.abi }}";
            systemImageType = "default";
            package = "com.termux";
            activity = ".app.TermuxActivity";
          }' > android-emulator.nix

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Start Android Emulator with Termux
        uses: cachix/nix-action@v4
        with:
          nix-file: android-emulator.nix

      - name: Execute Script Inside Termux
        run: |
          adb shell am start -n com.termux/.app.TermuxActivity
          sleep 5
          adb shell "echo 'bash /data/data/com.termux/files/home/myscript.sh' | tee /data/data/com.termux/files/home/.bashrc"
          adb shell am force-stop com.termux
          adb shell am start -n com.termux/.app.TermuxActivity
          sleep 5

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Termux-Build-${{ matrix.abi }}
          path: output-folder/
